### ISSUE TITLE
need finger swap back , on the app

### ISSUE THREAD

**Issue by lpgfx007** [dxitltd/Classifapp-Issue-Tracking#6]
need finger swap back , on the app , wen user in items /page and other, swap back by finger on Eag on iPhone and i Pads

**Comment by dxitltd** [comment]
@lpgfx007  can you please explain what did you mean by this?

**Comment by lpgfx007** [comment]
[Messenger.zip](https://github.com/dxitltd/Classifapp-Issue-Tracking/files/3442828/Messenger.zip)
on the app, if we go to ads or something we need go to top left cornerback to get back, all ios app have swap back on age. finger swap , i hope you can get it, wen looking the video

**Comment by dxitltd** [comment]
We previously had this feature but disabled it because of a problem. The problem was when you navigate to the item detail page then keep swiping the slider images back this was also moving back to the previous page which is the home page. The slider image swiping back should not take to the back page. If we find a solution to this issue then we might enable this feature again.

**Comment by lpgfx007** [comment]
I think if we can make swiping back ,  sense  only bottom of the application allow will solution for that , top on the app will not work , and can go by back icon what we have , now . This  feature need most of apps have !

**Comment by dxitltd** [comment]
This has been done.
